# Generated by Django 5.2.12 on 2026-04-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_courseenrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='last_lesson_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
